services:
  mongo_db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: codeai
    volumes:
      - mongo_data:/data/db
  
  auth:
    image: ashutoshpaliwal26/code-editor:auth
    restart: always
    ports: 
      - "8000:8000"
    environment:
      MONGO_DB_URI: ${MONGO_DB_URI}
    depends_on:
      - mongo_db

  cmd:
    image: ashutoshpaliwal26/code-editor:cmd
    ports:
      - "8001:8001"

volumes:
  mongo_data: