services:
  # mongo_db:
  #   image: mongo
  #   container_name: db
  #   restart: always
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: admin
  #     MONGO_INITDB_ROOT_PASSWORD: root
  #     MONGO_INITDB_DATABASE: codeai
  #   volumes:
  #     - mongo_data:/data/db
  #   networks:
  #     - default

  
  auth:
    image: ashutoshpaliwal26/code-editor:authentication
    container_name: auth
    restart: always
    ports: 
      - "8000:8000"
    environment:
      MONGO_DB_URI: ${MONGO_DB_URI}
      SECRET_JWT_KEY: ${SECRET_JWT_KEY}
    networks:
      - default

      
  cmd:
    image: ashutoshpaliwal26/code-editor:cmd
    container_name: cmd
    ports:
      - "8001:8001"
    networks:
      - default
