name: Docker Image CI [IMG > TAG { AUTH }]

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Verify Docker login
        run: docker info

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker Image AUTH SERVICE
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/code-editor:authentication

      - name: Build and Push Docker Image CMD SERVICE
        uses: docker/build-push-action@v6
        with:
          context: ./apps/cmd
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/code-editor:cmd
