name: Deploy to Google Cloud Provider Computer Engine.

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - 
                name: Checkout Repo
                uses: actions/checkout@v4
            
            -
                name: Set up Google Cloud SDK
                uses: google-github-actions/setup-gcloud@v2
                with:
                    project_id: ${{ secrets.GCP_PROJECT }}
                    service_account_key: ${{ secrets.GCP_SA_KEY }}
                    export_default_credentials: true

            -
                name: Add SSH Key
                run: |
                    mkdir -p ~/.ssh
                    echo "${{ secrets.GCE_SSH_KEY }}" > ~/.ssh/google_compute_engine
                    chmod 600 ~/.ssh/google_compute_engine

            -
                name: SSH into GCE and Deploy
                run: |
                    gcloud compute ssh ${{ secrets.GCE_SSH_USER }}@${{ secrets.GCE_INSTANCE }} \
                        --zone=${{ secrets.GCP_ZONE }} \
                        --command="cd /path/to/your/app && git pull origin main && docker-compose down && docker-compose up -d"


            