name: Deploy to Google Cloud Provider Compute Engine

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT }}

      - name: SSH into GCE and Deploy
        run: |
          gcloud compute ssh ${{ secrets.GCE_SSH_USER }}@${{ secrets.GCE_INSTANCE }} \
            --zone=${{ secrets.GCP_ZONE }} \
            --quiet \
            --command="bash -c '
              sudo git pull origin && cd /home/ashutoshpaliwal26/codai/script && \
                sudo chown ashutoshpaliwal26 deploy.sh && \
                chmod +x deploy.sh && ./deploy.sh
            '"
